version: 0.0
os: linux

files:
  - source: application.jar
    destination: /home/ubuntu/app
  - source: scripts
    destination: /home/ubuntu

permissions:
  - object: /home/ubuntu/scripts
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
  - object: /home/ubuntu/app
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: ubuntu

  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/set_permissions.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30
      runas: ubuntu

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 30
      runas: ubuntu