version: 0.0
os: linux

files:
  - source: application.jar
    destination: /home/ec2-user/app
  - source: scripts
    destination: /home/ec2-user

permissions:
  - object: /home/ec2-user
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ec2-user

  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/set_permissions.sh
      timeout: 120
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
      runas: ec2-user

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: ec2-user