version: 0.0
os: linux

files:
  - source: application.jar
    destination: /home/ec2-user/app
  - source: scripts
    destination: /home/ec2-user

permissions:
  - object: /home/ec2-user/scripts
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/set_permissions.sh
      timeout: 120
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 180  # 3 minutos para iniciar
      runas: ec2-user