version: 0.2

env:
  variables:
    MAVEN_OPTS: "-Xmx2048m -XX:MaxMetaspaceSize=512m"
    # ESTOS 4 VALORES SE CONFIGURAN EN CODEBUILD CONSOLE
    GOOGLE_CLIENT_ID: ""
    GOOGLE_CLIENT_SECRET: ""
    SPOTIFY_CLIENT_ID: ""
    SPOTIFY_CLIENT_SECRET: ""

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - chmod +x mvnw

  build:
    commands:
      # Solo compilar
      - ./mvnw clean package -DskipTests --batch-mode
      - echo "✅ Build completado"

  post_build:
    commands:
      - echo "=== CREANDO PAQUETE DE DEPLOYMENT ==="

      # 1. Crear estructura
      - mkdir -p codedeploy

      # 2. Copiar JAR
      - cp target/*.jar codedeploy/application.jar

      # 3. Copiar APPSPEC
      - cp appspec.yml codedeploy/

      # 4. Crear ARCHIVO DE SECRETS SEPARADO
      - cat > codedeploy/application-secrets.properties << EOF
# Secrets inyectados durante el build
# NO MODIFICAR MANUALMENTE
  GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
  GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
  SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
  SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
  EOF

# 5. Crear SCRIPT PEQUEÑO para cargar secrets (se ejecuta antes de start_server.sh)
- cat > codedeploy/scripts/load_secrets.sh << 'EOF'
#!/bin/bash
# Script simple para cargar secrets
  echo "Cargando secrets..."
  
  SECRETS_FILE="/home/ec2-user/application-secrets.properties"
  if [ -f "$SECRETS_FILE" ]; then
  # Leer y exportar variables
  while IFS='=' read -r key value; do
  if [[ ! $key =~ ^# ]] && [[ -n $key ]]; then
  export "$key"="$value"
  echo "✓ $key configurado"
  fi
  done < "$SECRETS_FILE"
  
  # Configurar redirect URI dinámico
  PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo "localhost")
  export SPOTIFY_REDIRECT_URI="http://${PUBLIC_IP}:8080/callback"
echo "✓ SPOTIFY_REDIRECT_URI: $SPOTIFY_REDIRECT_URI"
  else
  echo "⚠️  Archivo de secrets no encontrado"
  fi
  EOF
  
  # 6. Copiar TUS SCRIPTS EXISTENTES
  - chmod +x scripts/*
  - cp -r scripts codedeploy/
  
  # 7. Modificar TU start_server.sh para usar load_secrets.sh
  - cat >> codedeploy/scripts/start_server.sh << 'EOF'
  
  # ============================================
  # SECCION AGREGADA PARA CARGAR SECRETS
  # ============================================
  if [ -f "/home/ec2-user/scripts/load_secrets.sh" ]; then
  echo "=== CARGANDO SECRETS ==="
  source /home/ec2-user/scripts/load_secrets.sh
  fi
  # ============================================
  EOF
  
  # 8. Dar permisos al nuevo script
  - chmod +x codedeploy/scripts/load_secrets.sh
  
  # 9. Crear ZIP
  - cd codedeploy && zip -r ../deployment-package.zip .
  - echo "✅ Paquete creado con secrets"

artifacts:
  files:
    - deployment-package.zip