version: 0.2

env:
  variables:
    MAVEN_OPTS: "-Xmx2048m -XX:MaxMetaspaceSize=512m"
    # AGREGAR ESTAS 4 LÍNEAS
    GOOGLE_CLIENT_ID: ""
    GOOGLE_CLIENT_SECRET: ""
    SPOTIFY_CLIENT_ID: ""
    SPOTIFY_CLIENT_SECRET: ""

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "=== INSTALANDO DEPENDENCIAS ==="
      - java -version
      - chmod +x mvnw
      - ./mvnw --version

  build:
    commands:
      - echo "=== COMPILANDO APLICACIÓN ==="
      - ./mvnw clean package -DskipTests --batch-mode
      - echo "✅ Build completado exitosamente"

  post_build:
    commands:
      - echo "=== PREPARANDO DEPLOYMENT ==="
      - mkdir -p codedeploy
      - cp target/*.jar codedeploy/application.jar
      - cp appspec.yml codedeploy/
      - chmod +x scripts/*
      - cp -r scripts codedeploy/

      # AGREGAR: Crear archivo de secrets
      - echo "GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}" > codedeploy/application-secrets.env
      - echo "GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}" >> codedeploy/application-secrets.env
      - echo "SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}" >> codedeploy/application-secrets.env
      - echo "SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}" >> codedeploy/application-secrets.env

      # AGREGAR: Crear script load_secrets.sh simple
      - echo '#!/bin/bash' > codedeploy/scripts/load_secrets.sh
      - echo '[ -f "/home/ec2-user/application-secrets.env" ] && source /home/ec2-user/application-secrets.env' >> codedeploy/scripts/load_secrets.sh
      - echo 'export SPOTIFY_REDIRECT_URI="http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo localhost):8080/callback"' >> codedeploy/scripts/load_secrets.sh
      - chmod +x codedeploy/scripts/load_secrets.sh

      - cd codedeploy && zip -r ../deployment-package.zip .
      - cd ..
      - echo "✅ Paquete de deployment creado"

artifacts:
  files:
    - deployment-package.zip
  discard-paths: no

cache:
  paths:
    - '/root/.m2/**/*'