version: 0.2

env:
  variables:
    MAVEN_OPTS: "-Xmx2048m -XX:MaxMetaspaceSize=512m"

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "=== INSTALANDO DEPENDENCIAS ==="
      - java -version
      - chmod +x mvnw
      - ./mvnw --version

  build:
    commands:
      - echo "=== COMPILANDO APLICACIÓN ==="
      - ./mvnw clean package -DskipTests --batch-mode
      - echo "✅ Build completado exitosamente"

  post_build:
    commands:
      - echo "=== PREPARANDO DEPLOYMENT ==="
      - mkdir -p codedeploy
      - cp target/*.jar codedeploy/application.jar
      - cp appspec.yml codedeploy/
      - chmod +x scripts/*
      - cp -r scripts codedeploy/
      - cd codedeploy && zip -r ../deployment-package.zip .
      - cd ..
      - echo "✅ Paquete de deployment creado"

artifacts:
  files:
    - deployment-package.zip
  discard-paths: no

cache:
  paths:
    - '/root/.m2/**/*'