version: 0.2

env:
  variables:
    MAVEN_OPTS: "-Xmx2048m -XX:MaxMetaspaceSize=512m"

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "=== INICIANDO INSTALACIÓN ==="
      - java -version
      - chmod +x mvnw
      - ./mvnw --version
      - echo "Descargando dependencias..."
      - ./mvnw dependency:resolve --batch-mode

  build:
    commands:
      - echo "=== EJECUTANDO BUILD COMPLETO ==="
      # Primero compilar para verificar sintaxis
      - ./mvnw clean compile --batch-mode

      # Luego ejecutar tests separadamente
      - echo "Ejecutando pruebas unitarias..."
      - ./mvnw test --batch-mode

      # Finalmente empaquetar (esto ejecutará verify sin fallar por tests)
      - echo "Generando artefacto..."
      - ./mvnw package -DskipTests=false --batch-mode

  post_build:
    commands:
      - echo "=== VERIFICANDO RESULTADOS ==="
      - find target/ -name "*.jar" -type f
      - ls -la target/
      - echo "✅ BUILD EXITOSO"

artifacts:
  files:
    - target/*.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'